### ISSUE TITLE
support argnames as list/tuple

### ISSUE THREAD

**Issue by brondsem** [takemikami/intellij-pytest-parametrize-inlay-hint#3]
This a very helpful plugin, thanks!

Would it be possible to support argnames as a list/tuple, not just a str?  For example this syntax is valid but the plugin doesn't handle it:

```python
@pytest.mark.parametrize(['input', 'output'], [
    ...
```

https://docs.pytest.org/en/7.1.x/reference/reference.html?highlight=argnames#pytest.Metafunc.parametrize

**Comment by takemikami** [comment]
support at 0.0.2

![スクリーンショット 2023-06-13 120347](https://github.com/takemikami/intellij-pytest-parametrize-inlay-hint/assets/1129652/59087e70-ab64-4bbc-9d89-edfd43626187)
